#!/usr/bin/env python3

currInput = int(input())
totalOdd = currInput * (currInput % 2)
currInput = int(input())
totalOdd += currInput * (currInput % 2)
currInput = int(input())
totalOdd += currInput * (currInput % 2)
currInput = int(input())
totalOdd += currInput * (currInput % 2)
currInput = int(input())
totalOdd += currInput * (currInput % 2)
currInput = int(input())
totalOdd += currInput * (currInput % 2)
currInput = int(input())
totalOdd += currInput * (currInput % 2)
currInput = int(input())
totalOdd += currInput * (currInput % 2)
currInput = int(input())
totalOdd += currInput * (currInput % 2)
currInput = int(input())
totalOdd += currInput * (currInput % 2)
print(totalOdd)
